name: hello world
on : workflow_dispatch
jobs: 
   build:
      runs-on: ubuntu-latest
      steps:
         - name: build step
           run: echo "A demo build"
   test:  
        runs-on: ubuntu-latest
        need: build
        steps:
           - name: test phase
             run: echo "running test case"
   deploy:
          runs-on: ubuntu-latest
          need: test
          steps:
             - name: deploy the appl
               run: echo "deploying the application"
